# Generated by Django 2.0.3 on 2018-04-26 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=15, verbose_name='姓')),
                ('last_name', models.CharField(max_length=15, verbose_name='名')),
                ('sex', models.CharField(choices=[('M', 'Man'), ('W', 'Woman')], max_length=1, verbose_name='性別')),
                ('period', models.IntegerField(max_length=2, verbose_name='期')),
                ('style', models.CharField(choices=[('Fr', 'Fr'), ('Ba', 'Ba'), ('Br', 'Br'), ('Fly', 'Fly'), ('IM', 'IM')], max_length=4, verbose_name='スタイル')),
                ('is_manager', models.BooleanField(default=False, verbose_name='マネジャー')),
                ('is_OBOG', models.BooleanField(default=False, verbose_name='既卒')),
                ('is_courch', models.BooleanField(default=False, verbose_name='コーチ')),
                ('is_master', models.BooleanField(default=False, verbose_name='管理者')),
            ],
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
