# Generated by Django 2.0.3 on 2018-04-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_auto_20180426_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menue',
            name='distance',
            field=models.IntegerField(choices=[(25, 25), (50, 50), (100, 100), (200, 200), (400, 400), (800, 800)], verbose_name='距離'),
        ),
    ]
