# Generated by Django 2.0.3 on 2018-04-27 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0006_auto_20180426_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menue',
            name='count',
        ),
    ]
