# Generated by Django 2.0.3 on 2018-05-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0008_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(choices=[(25, 25), (50, 50), (100, 100), (200, 200), (400, 400), (800, 800)], verbose_name='距離')),
            ],
        ),
        migrations.CreateModel(
            name='Result_Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_minutes', models.DurationField(default=0, verbose_name='分')),
                ('time_seconds', models.DurationField(verbose_name='秒')),
                ('time_seconds_micro', models.DurationField(verbose_name='少数点以下')),
            ],
        ),
        migrations.RemoveField(
            model_name='time_result',
            name='menue',
        ),
        migrations.RemoveField(
            model_name='time_result',
            name='person',
        ),
        migrations.RemoveField(
            model_name='menue',
            name='distance',
        ),
        migrations.DeleteModel(
            name='Time_Result',
        ),
    ]
