# Generated by Django 2.0.3 on 2018-05-27 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0009_auto_20180525_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result_time',
            name='time_minutes',
            field=models.IntegerField(default=0, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='result_time',
            name='time_seconds',
            field=models.IntegerField(default=0, verbose_name=':'),
        ),
        migrations.AlterField(
            model_name='result_time',
            name='time_seconds_micro',
            field=models.IntegerField(default=0, verbose_name='.'),
        ),
    ]
