# Generated by Django 2.0.3 on 2018-05-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0010_auto_20180528_0841'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Distance',
        ),
        migrations.AddField(
            model_name='result_time',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='result_time',
            name='distance',
            field=models.IntegerField(choices=[(25, 25), (50, 50), (100, 100), (200, 200), (400, 400), (800, 800)], null=True),
        ),
    ]
