# Generated by Django 2.0.3 on 2018-05-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0011_auto_20180528_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='generation',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='sex',
            field=models.CharField(choices=[('M', 'Man'), ('W', 'Woman')], max_length=5, null=True),
        ),
    ]
