# Generated by Django 2.0.3 on 2018-05-29 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0012_auto_20180529_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('distance', models.IntegerField(choices=[(25, 25), (50, 50), (100, 100), (200, 200), (400, 400), (800, 800)], null=True)),
                ('menue_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='record.Menue')),
            ],
        ),
        migrations.RemoveField(
            model_name='result_time',
            name='date',
        ),
        migrations.RemoveField(
            model_name='result_time',
            name='distance',
        ),
        migrations.AlterField(
            model_name='users',
            name='generation',
            field=models.IntegerField(default=47, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='record.Users'),
        ),
        migrations.AddField(
            model_name='result_time',
            name='traning_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='record.Training'),
        ),
    ]
