# Generated by Django 2.0.3 on 2018-05-30 21:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0015_auto_20180530_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='date',
            field=models.DateField(default=datetime.date(2018, 5, 31), null=True),
        ),
    ]
