# Generated by Django 2.0.3 on 2018-06-04 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0018_auto_20180604_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result_time',
            name='training',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='record.Training'),
        ),
    ]
