# Generated by Django 2.0.3 on 2018-06-16 00:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0019_auto_20180604_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='result_time',
            name='rest',
            field=models.BooleanField(default=False, verbose_name='レスト'),
        ),
        migrations.AddField(
            model_name='result_time',
            name='second',
            field=models.IntegerField(blank=True, null=True, verbose_name='タイム[s]'),
        ),
        migrations.AlterField(
            model_name='training',
            name='date',
            field=models.DateField(default=datetime.date(2018, 6, 16), null=True),
        ),
    ]
