# Generated by Django 2.0.3 on 2018-06-16 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0020_auto_20180616_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='result_time',
            name='num_of_swim',
            field=models.IntegerField(null=True, verbose_name='本数'),
        ),
        migrations.AlterField(
            model_name='result_time',
            name='second',
            field=models.FloatField(blank=True, null=True, verbose_name='タイム[s]'),
        ),
    ]
