# Generated by Django 2.0.3 on 2018-06-16 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0021_auto_20180616_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result_time',
            name='time_minutes',
        ),
        migrations.RemoveField(
            model_name='result_time',
            name='time_seconds',
        ),
        migrations.RemoveField(
            model_name='result_time',
            name='time_seconds_micro',
        ),
    ]
