# Generated by Django 2.0.6 on 2018-06-21 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0022_auto_20180616_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='date',
            field=models.DateField(default=datetime.date(2018, 6, 21), null=True),
        ),
    ]
