# Generated by Django 2.0.6 on 2018-06-23 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0023_auto_20180621_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='result_time',
            name='time_str',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='タイム'),
        ),
        migrations.AlterField(
            model_name='training',
            name='date',
            field=models.DateField(default=datetime.date(2018, 6, 23), null=True),
        ),
    ]
