# Generated by Django 2.0.6 on 2018-06-27 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0026_auto_20180627_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='date',
            field=models.DateField(default=datetime.date(2018, 6, 28), null=True),
        ),
    ]
