# Generated by Django 2.0.6 on 2018-06-29 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0027_auto_20180628_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='familyname',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='姓'),
        ),
        migrations.AddField(
            model_name='user_info',
            name='firstname',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='名'),
        ),
        migrations.AlterField(
            model_name='training',
            name='date',
            field=models.DateField(default=datetime.date(2018, 6, 29), null=True),
        ),
    ]
