# Generated by Django 2.0.2 on 2018-11-14 22:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0028_auto_20180629_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='date',
            field=models.DateField(default=datetime.date(2018, 11, 15), null=True),
        ),
    ]
