# Generated by Django 2.0.2 on 2018-11-28 09:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0030_auto_20181128_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='menue_name',
        ),
        migrations.RemoveField(
            model_name='training',
            name='user',
        ),
        migrations.RenameField(
            model_name='result_time',
            old_name='num_of_swim',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='result_time',
            old_name='second',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='result_time',
            name='time_str',
        ),
        migrations.RemoveField(
            model_name='result_time',
            name='training',
        ),
        migrations.AddField(
            model_name='result_time',
            name='trainingmenu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='record.TrainingMenu'),
        ),
        migrations.AlterField(
            model_name='daymenu',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 11, 28, 9, 43, 0, 728048, tzinfo=utc), null=True),
        ),
        migrations.DeleteModel(
            name='Training',
        ),
    ]
