# Generated by Django 2.0.2 on 2018-11-28 09:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0031_auto_20181128_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daymenu',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
