# Generated by Django 2.0.2 on 2018-11-28 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0032_auto_20181128_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingmenu',
            name='distance',
            field=models.IntegerField(choices=[(25, 25), (50, 50), (100, 100), (200, 200), (400, 400), (800, 800)]),
        ),
        migrations.AlterField(
            model_name='trainingmenu',
            name='menu_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='record.Menue'),
        ),
    ]
