# Generated by Django 2.0.2 on 2018-12-02 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0033_auto_20181128_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingmenu',
            name='daymenu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainingmanus', to='record.DayMenu'),
        ),
    ]
