# Generated by Django 2.0.2 on 2018-12-02 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0035_auto_20181202_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rap_Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField(blank=True, null=True, verbose_name='タイム[s]')),
            ],
        ),
        migrations.AlterField(
            model_name='result_time',
            name='trainingmenu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='times', to='record.TrainingMenu'),
        ),
        migrations.AddField(
            model_name='rap_time',
            name='result_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raps', to='record.Result_Time'),
        ),
    ]
