# Generated by Django 2.0.2 on 2018-12-06 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0036_auto_20181202_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingmenu',
            name='menu_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='record.Menue'),
        ),
    ]
