version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.5
    working_directory: /home/circleci/project/swim
    steps:
      - checkout
      - run:
          name: chown site-packages
          command: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages/
      - run:
          name: chown usr/bin
          command: sudo chown -R circleci:circleci /usr/local/bin
      - run:
          name: pip install
          command: |
            pip install -r requirements.txt
      - run:
          name: run test
          command: |
            cd swim
            python ./manage.py test
