version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.5
    steps:
      - checkout
      - run:
          name: run test
          command: |
            cd swim
            python ./manage.py test
