version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.5
    steps:
      - checkout
      - run:
          name: chown
          command: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages/
      - run:
          name: pip install
          command: |
            cd swim
            pip install -r requirements.txt
      - run:
          name: run test
          command: |
            python ./manage.py test
