# Generated by Django 2.0.3 on 2018-06-07 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tex',
            name='comment',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tex',
            name='text',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tex',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
