# Generated by Django 2.0.3 on 2018-06-07 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20180608_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='tex',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
